apiVersion: v2
name: securegist
description: A Helm chart for SecureGist application
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: "18.2.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: traefik
    version: 38.0.1
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
